name: cph200b-project-1
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - comm=0.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.6.4
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmpdec=4.0.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.15
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.8.0
  - pip=24.2
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python_abi=3.13
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.8.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - wcwidth=0.2.5
  - wheel=0.44.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - attrs==25.1.0
      - autograd==1.7.0
      - autograd-gamma==0.5.0
      - brotli==1.1.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - chex==0.1.88
      - conda-pack==0.8.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - etils==1.12.0
      - feather-format==0.4.1
      - filelock==3.13.1
      - flax==0.10.3
      - fonttools==4.56.0
      - formulaic==1.1.1
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - h5py==3.13.0
      - humanize==4.12.0
      - idna==3.10
      - importlib-resources==6.5.2
      - inflate64==1.0.1
      - interface-meta==1.3.0
      - jax==0.5.0
      - jaxlib==0.5.0
      - jaxopt==0.8.3
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lifelines==0.30.0
      - lightning==2.5.0.post0
      - lightning-utilities==0.12.0
      - llvmlite==0.44.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multivolumefile==0.2.3
      - networkx==3.3
      - numba==0.61.0
      - numpy==2.1.0
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.11.5
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.1.0
      - propcache==0.3.0
      - protobuf==5.29.3
      - py7zr==0.22.0
      - pyarrow==19.0.1
      - pybcj==1.0.3
      - pycox==0.3.0
      - pycryptodomex==3.21.0
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pyppmd==1.1.1
      - pytorch-lightning==2.5.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzstd==0.16.2
      - requests==2.32.3
      - rich==13.9.4
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - simplejson==3.19.3
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tensorstore==0.1.71
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - toolz==1.0.0
      - torch==2.6.0+cpu
      - torchaudio==2.6.0+cpu
      - torchmetrics==1.6.1
      - torchtuples==0.2.2
      - torchvision==0.21.0+cpu
      - tqdm==4.67.1
      - treescope==0.1.8
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - wrapt==1.17.2
      - yarl==1.18.3
      - zipp==3.21.0
